name: Ready for Review Rebase

on:
  pull_request:
    types: [ready_for_review]

jobs:
  add_label:
    if: contains(github.event.pull_request.labels.*.name, 'CI/run-draft') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: add rebase label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: rebase

      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: automatic rebase
        uses: cirrus-actions/rebase@1.7
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: remove label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: rebase
