on:
  pull_request:
    types: [opened, reopened]

name: Pull Request

permissions:
  pull-requests: write
  contents: read

jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-slim
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@9558557c5c4816f38bd06176fbc324ba14bb3160 # v1.6.2
